export const actionTypes = {
    UPDATE_BY_PATH_NAME: "UPDATE_BY_PATH_NAME",
    ADD_BY_PATH_NAME: "ADD_BY_PATH_NAME",
    DELETE_BY_PATH_NAME: "DELETE_BY_PATH_NAME",
    CLEAR_PERSIST: "CLEAR_PERSISTs"
};
